// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGbI7CWXWUT3U5NWAYPVoFLMDEyxY5eQ',
    appId: '1:867156424639:web:d038703345efc48643130a',
    messagingSenderId: '867156424639',
    projectId: 'aplicativo-de-meditacao',
    authDomain: 'aplicativo-de-meditacao.firebaseapp.com',
    databaseURL: 'https://aplicativo-de-meditacao-default-rtdb.firebaseio.com',
    storageBucket: 'aplicativo-de-meditacao.appspot.com',
    measurementId: 'G-NPHX1Q263J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgXK03ruiMIH-fhS5zhtZNzgGGfssYeTE',
    appId: '1:867156424639:android:303027909424dd7443130a',
    messagingSenderId: '867156424639',
    projectId: 'aplicativo-de-meditacao',
    databaseURL: 'https://aplicativo-de-meditacao-default-rtdb.firebaseio.com',
    storageBucket: 'aplicativo-de-meditacao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJGtpoPsRHURmDbrfOsPGLMHDCKgtXe5Q',
    appId: '1:867156424639:ios:9e8c0d2b7ba86eb143130a',
    messagingSenderId: '867156424639',
    projectId: 'aplicativo-de-meditacao',
    databaseURL: 'https://aplicativo-de-meditacao-default-rtdb.firebaseio.com',
    storageBucket: 'aplicativo-de-meditacao.appspot.com',
    iosBundleId: 'com.example.novoAppMeditacao',
  );
}
